### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by seterrychen** [libopenstorage/openstorage#136]
When I using `docker volume ls`, it took longer time than expected and error message displayed.

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo time docker volume ls
list nfs: Post http://%2Frun%2Fdocker%2Fplugins%2Fnfs.sock/VolumeDriver.List: http: ContentLength=3 with Body length 0
DRIVER              VOLUME NAME
nfs                 test
0.02user 0.00system 0:15.04elapsed 0%CPU (0avgtext+0avgdata 15256maxresident)k
0inputs+0outputs (0major+4156minor)pagefaults 0swaps
```

and Output of osd:

```
2016/04/11 07:08:36 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 30 [running]:
net/http.(*conn).serve.func1(0xc8202129a0, 0x7f51835664a0, 0xc820026ae8)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/libopenstorage/openstorage/volume.match(0xc8201e8840, 0x0, 0x0, 0xfc81e0)
	/home/vagrant/gopath/src/github.com/libopenstorage/openstorage/volume/enumerator.go:206 +0x1c
github.com/libopenstorage/openstorage/volume.(*DefaultEnumerator).Enumerate(0xc82016f500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/gopath/src/github.com/libopenstorage/openstorage/volume/enumerator.go:123 +0x2c3
github.com/libopenstorage/openstorage/api/server.(*driver).list(0xc82019ee40, 0x7f51835665f0, 0xc820212d10, 0xc8201f96c0)
	/home/vagrant/gopath/src/github.com/libopenstorage/openstorage/api/server/docker.go:314 +0x39f
github.com/libopenstorage/openstorage/api/server.(*driver).(github.com/libopenstorage/openstorage/api/server.list)-fm(0x7f51835665f0, 0xc820212d10, 0xc8201f96c0)
	/home/vagrant/gopath/src/github.com/libopenstorage/openstorage/api/server/docker.go:81 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc8201ad7f0, 0x7f51835665f0, 0xc820212d10, 0xc8201f96c0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/libopenstorage/openstorage/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc820192aa0, 0x7f51835665f0, 0xc820212d10, 0xc8201f96c0)
	/home/vagrant/gopath/src/github.com/libopenstorage/openstorage/vendor/github.com/gorilla/mux/mux.go:103 +0x270
net/http.serverHandler.ServeHTTP(0xc8201a5aa0, 0x7f51835665f0, 0xc820212d10, 0xc8201f96c0)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8202129a0)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
```

go version: go1.5.3 linux/amd64
osd version: v1

**Comment by jvinod** [comment]
ping @adityadani

**Comment by adityadani** [comment]
@seterrychen : I was unable to reproduce this issue on my setup. 
I created nfs volumes using osd cli as well as docker cli with driver option and was able to enumerate without panic.

Which docker version are you using ?
Also just to confirm, how did you create your "test" volume ?

**Comment by seterrychen** [comment]
@adityadani: docker version is 1.11.0 and using `docker volume create -d nfs --name test`.

I also using `Vagrant` to [create environment](https://github.com/seterrychen/openstorage-env), it may help you reproduce this issue.
