### ISSUE TITLE
panic while creating nfs volume 

### ISSUE THREAD

**Issue by kunalkushwaha** [libopenstorage/openstorage#151]
This is with latest code of osd, build with ``go 1.6`` . 

```
root@mac-dev:/home/kunal/work# ../go/bin/osd -d -f config.yaml
INFO[0000] Starting volume driver: nfs
INFO[0000] NFS driver initializing with 129.60.241.239:/Users/kunalkushwaha/work/test
INFO[0000] NFS initialized and driver mounted at:  /var/lib/openstorage/nfs/
INFO[0000] Starting REST service on socket : /var/lib/osd/driver/nfs.sock
INFO[0000] Starting REST service on socket : /run/docker/plugins/nfs.sock
WARN[0144] 404   Failed to locate volume: Cannot locate volume vol2  Driver=nfs ID=vol2 Request=get
INFO[0144]                                               Driver=nfs ID=vol2 Request=create
2016/05/10 15:27:19 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*conn).serve.func1(0xc8201aba80)
        /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0xee6960, 0xc82000e120)
        /usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/libopenstorage/openstorage/volume/drivers/common.match(0xc8200bc600, 0x0, 0x0, 0x10414a0)
        /home/kunal/go/src/github.com/libopenstorage/openstorage/volume/drivers/common/default_store_enumerator.go:184 +0x1c
github.com/libopenstorage/openstorage/volume/drivers/common.(*defaultStoreEnumerator).Enumerate(0xc820195500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/kunal/go/src/github.com/libopenstorage/openstorage/volume/drivers/common/default_store_enumerator.go:101 +0x2c1
github.com/libopenstorage/openstorage/volume/drivers/nfs.(*driver).Enumerate(0xc82019f5e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        <autogenerated>:6 +0x8e
github.com/libopenstorage/openstorage/api/server.(*driver).list(0xc8201b4930, 0x7fe49a8a82b8, 0xc820202340, 0xc8200c3ea0)
        /home/kunal/go/src/github.com/libopenstorage/openstorage/api/server/docker.go:319 +0x2d0
github.com/libopenstorage/openstorage/api/server.(*driver).(github.com/libopenstorage/openstorage/api/server.list)-fm(0x7fe49a8a82b8, 0xc820202340, 0xc8200c3ea0)
        /home/kunal/go/src/github.com/libopenstorage/openstorage/api/server/docker.go:82 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc8201c6670, 0x7fe49a8a82b8, 0xc820202340, 0xc8200c3ea0)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/libopenstorage/openstorage/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc8201cc050, 0x7fe49a8a82b8, 0xc820202340, 0xc8200c3ea0)
        /home/kunal/go/src/github.com/libopenstorage/openstorage/vendor/github.com/gorilla/mux/mux.go:103 +0x270
net/http.serverHandler.ServeHTTP(0xc8201ab900, 0x7fe49a8a82b8, 0xc820202340, 0xc8200c3ea0)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8201aba80)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
^[^C
```

**Comment by jvinod** [comment]
@rodriguise could you look?

**Comment by jvinod** [comment]
Looks like the same as https://github.com/libopenstorage/openstorage/issues/136
This is fixed
